"use strict";
const $ = (id) => document.getElementById(id);
const methodNames = {E0:"E0 · 零残差",E1:"E1 · TRAIN 检索",E2:"E2 · Diffusion K1",teacher:"固定 Teacher"};
let bundle, plots, media, active="all";
const number=(v,d=3)=>Number.isFinite(v)?v.toFixed(d):"—";
const option=(value,text)=>new Option(text,value);
const mediaPath=(v)=>typeof v==="string"?v:(v?.path||v?.file||v?.url||"");
function makeLink(path,text){const a=document.createElement("a");a.href=path;a.textContent=text;return a;}
function taskLabel(r){return r.slot_id.startsWith("TEST_")?`TEST ${r.slot_id.slice(5,7)} · ${r.task_id}`:`${r.slot_id} · ${r.full_task_success?"首个非零完整示范":"教师失败前缀"}`;}
function selectedGroup(){const value=$("task-select").value;return media.records.filter(r=>(r.slot_id.startsWith("TEST_")?r.task_id:r.slot_id)===value);}
function updateMethods(){const current=$("method-select").value;$("method-select").replaceChildren();selectedGroup().forEach(r=>$("method-select").add(option(r.slot_id,methodNames[r.method]||r.method||r.slot_id)));if([...$("method-select").options].some(o=>o.value===current))$("method-select").value=current;$("method-select").disabled=selectedGroup().length===1;updateReplay();}
function updateReplay(){const r=media.records.find(x=>x.slot_id===$("method-select").value);if(!r)return;const view=$("view-select").value;const path=mediaPath(r.videos[view]);const player=$("main-player");player.pause();player.src=path;player.poster=mediaPath(r.preview);const end=r.source_end_s??r.simulation_horizon_s??r.actual_horizon_s;const okay=!!r.full_task_success;$("replay-status").className="replay-status"+(okay?"":" failed");$("replay-status").textContent=`${r.slot_id} · ${okay?"完整 Task 与独立验收 PASS":"FAIL · 原工作域守卫拒绝，仅保存前缀"} · 实际状态 0–${number(end,3)} s`;
$("replay-caption").textContent=`保存 qpos/qvel → mj_forward 渲染，未执行 mj_step。${r.fps||15} FPS；${okay?"实际任务时长 27 s。":"拒绝后没有后续状态，不补齐至 27 s。"} CFR 编码含末态并按整帧取整，文件时长稍长；实际状态范围以保存时标为准。原基础参考 / 残差参考 / 实际轨迹分别标注。`;
$("media-links").replaceChildren(makeLink(path,"打开当前 MP4 ↗"),makeLink(mediaPath(r.preview),"预览图 ↗"));
const group=selectedGroup();$("paired-comparison").hidden=group.length!==3;$("paired-players").replaceChildren();if(group.length===3){group.forEach(x=>{const a=document.createElement("article"),h=document.createElement("h3"),v=document.createElement("video"),p=document.createElement("p");h.textContent=methodNames[x.method]||x.method;v.controls=true;v.preload="none";v.playsInline=true;v.src=mediaPath(x.videos[view]);v.poster=mediaPath(x.preview);p.textContent=x.full_task_success?"完整 Task PASS":`FAIL · 前缀至 ${number(x.source_end_s,3)} s`;a.append(h,v,p);$("paired-players").append(a);});}}
function showFigures(){const typed=$("figure-search").value.toLowerCase().trim();const aliases={"路径":"path","训练":"train","间隙":"clearance","计时":"timing","安全":"geometry","基座":"base","参考":"reference","任务":"task","候选":"candidate","力矩":"torque","教师":"teacher"};const query=aliases[typed]||typed;const list=plots.panels.filter(p=>(active==="all"||active===p.category)&&(!query||(p.title+" "+p.caption+" "+p.category).toLowerCase().includes(query)));$("figure-grid").replaceChildren();if(!list.length){const p=document.createElement("p");p.className="empty";p.textContent="没有匹配的图表。";$("figure-grid").append(p);return;}list.forEach(p=>{const a=document.createElement("article"),link=document.createElement("a"),img=document.createElement("img"),copy=document.createElement("div"),h=document.createElement("h3"),caption=document.createElement("p"),source=document.createElement("p");a.className="figure-card";link.href=p.path;link.target="_blank";img.src=p.path;img.alt=p.title;img.loading="lazy";link.append(img);copy.className="copy";h.textContent=p.title;caption.textContent=p.caption;source.className="source";source.textContent=`${p.category} · 来源：${(p.source_paths||[]).map(x=>typeof x==="string"?x:x.path).join(" · ")}`;copy.append(h,caption,source);a.append(link,copy);$("figure-grid").append(a);});}
function setCategory(key){active=key;document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.key===key));$("replay-section").hidden=!["all","replay","paths","path","task","overview","Outcome","Actual paths"].includes(key);$("results-section").hidden=!["all","overview","task","outcomes","results","quality","paths","Outcome","Task acceptance","Quality"].includes(key);showFigures();}
function populateResults(){for(const r of bundle.TEST_rows){const tr=document.createElement("tr"),values=[r.slot_id,r.full_task_success?"PASS":"FAIL · 前缀",number(r.actual_steps*.002,3),number(r.actual_path_length_m?.continuum,6),number(r.whole_body_minimum_m*1000,6)+(r.full_task_success?"":" *"),number(r.minimum_by_class_m?.arm_obstacle*1000,6),number(r.command_intervention_rad_s?.rms,6),number(r.consumed_QP_offset_peak_m*1000,6)];values.forEach((v,i)=>{const td=document.createElement("td");td.textContent=v;if(i===1)td.className=r.full_task_success?"ok":"bad";tr.append(td);});$("results-body").append(tr);}}
async function start(){const responses=await Promise.all([fetch("dashboard_data.json"),fetch("plot_data.json"),fetch("videos.json")]);for(const r of responses){if(!r.ok)throw new Error(`${r.url}: HTTP ${r.status}`);} [bundle,plots,media]=await Promise.all(responses.map(r=>r.json()));
const categories=[...new Set(plots.panels.map(p=>p.category))];const titles={Outcome:"结果总览",Teacher:"全部教师",Learning:"训练与验证",Reference:"表示与候选","Actual paths":"路径与参考","Task acceptance":"任务验收",Geometry:"几何与安全",Dynamics:"基座与执行","PCC / contract":"PCC与执行合同",Timing:"时延与长尾",Quality:"完整任务质量",all:"全部当前结果",overview:"结果总览",outcomes:"结果与示范",training:"训练与验证",raw:"Raw 候选",representation:"解析表示",paths:"路径与参考",task:"任务要求",safety:"几何与安全",control:"执行与干预",timing:"计时与长尾",quality:"完整任务质量",base:"基座漂移",execution:"实际执行",reference:"参考消费",dataset:"数据覆盖"};
for(const key of ["all",...categories]){const b=document.createElement("button");b.type="button";b.dataset.key=key;b.textContent=titles[key]||key;b.onclick=()=>setCategory(key);document.querySelector(".tabs").append(b);}
const seen=new Set();for(const r of media.records){const key=r.slot_id.startsWith("TEST_")?r.task_id:r.slot_id;if(!seen.has(key)){seen.add(key);$("task-select").add(option(key,taskLabel(r)));}}
$("task-select").onchange=updateMethods;$("method-select").onchange=updateReplay;$("view-select").onchange=updateReplay;$("figure-search").oninput=showFigures;$("sync-play").onclick=async()=>{await Promise.all([...$("paired-players").querySelectorAll("video")].map(async v=>{v.currentTime=0;try{await v.play();}catch(error){console.warn(error);}}));};
$("source-identity").textContent=JSON.stringify(bundle.provenance,null,2);populateResults();updateMethods();setCategory("all");document.body.dataset.ready="true";}
start().catch(error=>{const p=document.createElement("p");p.className="loading-error";p.textContent=`数据加载失败：${error.message}。请从仓库根目录启动 python -m http.server，并用 http://127.0.0.1 访问此页面；GitHub 的 HTML 源码页不会执行交互。`;document.querySelector("main").prepend(p);document.body.dataset.ready="error";console.error(error);});
